/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3player;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author Anhad
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */   String username;

    public Home() {
        initComponents();
        jLabel10.setVisible(false);
jLabel11.setVisible(false);
jLabel12.setVisible(false);
jLabel13.setVisible(false);
 
    }
     public Home(String user)        
    {
        username=user;
        initComponents();
        jLabel18.setText(username);
     

jLabel10.setVisible(false);
jLabel11.setVisible(false);
jLabel12.setVisible(false);
jLabel13.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Help = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        Software = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        Developer = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        Version = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        Exitb1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Help.setTitle("Help");
        Help.setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        Help.setMinimumSize(new java.awt.Dimension(501, 279));
        Help.setResizable(false);
        Help.getContentPane().setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/howtopage (1).png"))); // NOI18N
        Help.getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 495, 279);

        Software.setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        Software.setMinimumSize(new java.awt.Dimension(501, 276));
        Software.setResizable(false);
        Software.getContentPane().setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/softwarepage (1).png"))); // NOI18N
        Software.getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 501, 280);

        Developer.setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        Developer.setMinimumSize(new java.awt.Dimension(501, 292));
        Developer.setResizable(false);
        Developer.getContentPane().setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/developerspage (1).png"))); // NOI18N
        Developer.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 500, 280);

        Version.setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        Version.setMinimumSize(new java.awt.Dimension(503, 295));
        Version.setResizable(false);
        Version.getContentPane().setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/versionpage (1).png"))); // NOI18N
        Version.getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 500, 274);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 563));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Exitb1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Exitb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        Exitb1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Exitb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Exitb1MouseReleased(evt);
            }
        });
        getContentPane().add(Exitb1);
        Exitb1.setBounds(970, 0, 30, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Software Information");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 170, 220, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Version Information");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 210, 220, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("How to use");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 250, 220, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Developers Information");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 130, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(950, 0, 30, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/music.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 130, 110, 110);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 153, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Search");
        jTextField2.setBorder(null);
        jTextField2.setHighlighter(null);
        jTextField2.setOpaque(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField2MouseReleased(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(880, 40, 120, 13);
        jTextField2.getAccessibleContext().setAccessibleParent(jTextField2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/search22.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(860, 30, 140, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WEATHER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(930, 410, 50, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/wall.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(870, 270, 110, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/weather.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(870, 410, 110, 110);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Guest");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(850, 90, 140, 20);

        jLabel19.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Hello            ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(870, 70, 130, 20);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/jar.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(340, 200, 280, 240);

        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 30, 250, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/new-background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 563);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseReleased
jTextField2.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2MouseReleased

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String gettext = jTextField2.getText();
             
            if(gettext.matches(".*mus.*"))
            {
                this.dispose();
                new MP3().setVisible(true);
            }
              if(gettext.matches(".*weat.*"))
            {
                this.dispose();
                new Weather_report().setVisible(true);
            }
                if(gettext.matches(".*log.*"))
            {
                this.dispose();
                new Login().setVisible(true);
            }
                   if(gettext.matches(".*regis.*"))
            {
                this.dispose();
                new Register().setVisible(true);
            }
                      if(gettext.matches(".*lock.*"))
            {
                this.dispose();
                new LockscreenGUI().setVisible(true);
            }
                      if(gettext.matches(".*wall.*"))
            {
                this.dispose();
                new Wallpaper().setVisible(true);
            }
                                if(gettext.matches(".*home.*"))
            {
                this.dispose();
                new Home().setVisible(true);
            }
                                if(gettext.matches(".*deve.*"))
            {
                
                Developer.setVisible(true);
            }
                                if(gettext.matches(".*soft.*"))
            {
                
                Software.setVisible(true);
            }
                                if(gettext.matches(".*vers.*"))
            {
                
                Version.setVisible(true);
            } 
                                if(gettext.matches(".*help.*"))
            {
                
                Help.setVisible(true);
            }                   
                                 if(gettext.matches(".*jar.*"))
            {
                this.dispose();
                new Jarvis().setVisible(true);
            }                   
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
String name = jLabel18.getText();
        this.dispose();
        new MP3(name).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
String name = jLabel18.getText();
        this.dispose();
new Weather_report(name).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
      String name = jLabel18.getText();
        this.dispose();
        new Wallpaper(name).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        this.setState(ICONIFIED);        
    }//GEN-LAST:event_jLabel2MouseReleased

    private void Exitb1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exitb1MouseReleased
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Exitb1MouseReleased

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
Help.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
Software.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
Developer.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
Version.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
String name = jLabel18.getText();
        this.dispose();
        jTextField2.setBackground(Color.red);
new Jarvis(name).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
        // TODO add your handling code here:
      jLabel10.setVisible(true);
      jLabel11.setVisible(true);
      jLabel12.setVisible(true);
      jLabel13.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Developer;
    private javax.swing.JLabel Exitb1;
    private javax.swing.JDialog Help;
    private javax.swing.JDialog Software;
    private javax.swing.JDialog Version;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
