package mp3player;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import static mp3player.Jarvis.extract;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * start.java
 *
 * Created on Nov 17, 2015, 5:25:48 AM
 */

/**
 *
 * @author Class XII
 */
public class Initialisation extends javax.swing.JFrame implements ActionListener {
    private static Timer timer;
    
    
    Mp3Player MC = new Mp3Player();
public void actionPerformed(ActionEvent e) {
    
    
        int n=jProgressBar1.getValue();
        int random= (int) Math.round(Math.random()*0.5);


         if (n <=99)
    {
          n++;
         
         
                  
          jProgressBar1.setValue(n+random);
    }

    else
    {
        timer.stop();
        
          this.dispose();
    new Login().setVisible(true);
            }
         
if(n==100){
    this.setVisible(false);
    try{
        Thread.sleep(1000);
    }catch(Exception a){}
  
}
    
    }
    /** Creates new form start */
    public Initialisation(){
        initComponents();
        
        MC.play("C:/softwares/Project_Jarvis/src/mp3player/Marvel");
        timer=new Timer(100,this);
        timer.start();
        
        
        
    }
 


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(180, 100, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1024, 576));
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        jProgressBar1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 102));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(-10, 550, 1040, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 540, 600, 10);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 140, 200, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/15740_Isomorphic_Algorithm2.gif"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 190, 200, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/jarvis_sound_scheme_real_jarvis_voice__by_bjayn-d7142vx.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Initialisation().setVisible(true);
              
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    

  }