/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3player;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Anhad
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
       initComponents();
       {
         
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Exitb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Exitbg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));
        setMinimumSize(new java.awt.Dimension(540, 268));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(540, 268));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(42, 26, 37));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Username");
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 130, 160, 20);

        Exitb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Exitb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        Exitb.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Exitb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitbMouseReleased(evt);
            }
        });
        getContentPane().add(Exitb);
        Exitb.setBounds(520, 0, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 0, 30, 20);

        Exitbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/exitmedium.png"))); // NOI18N
        getContentPane().add(Exitbg);
        Exitbg.setBounds(-70, 0, 600, 20);

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 140, 60, 50);

        jPasswordField1.setBackground(new java.awt.Color(42, 26, 37));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(30, 180, 160, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Login as Guest");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 220, 90, 15);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 220, 90, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/Login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 540, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbMouseReleased
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitbMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
      /**String username = jTextField1.getText();

if(username.equals("Username")){
    jTextField1.setText(null);
    jPasswordField1.setText("Password");
    }*/
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
    /**String password = new String(jPasswordField1.getPassword());
        if(password.equals("Password"))
    {
        jPasswordField1.setText(null);
        jTextField1.setText("Username");
    }
    */
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
this.dispose();
new Register().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
this.dispose();
new LockscreenGUI().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
    String user = jTextField1.getText();
    String pwd = new String(jPasswordField1.getPassword());
    
    if(jTextField1.getText().equals("")||jPasswordField1.equals(""))
{
    JOptionPane.showMessageDialog(this, "Invalid Entry");
}
    else
    try {
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Player","root","root");
    Statement stmt = (Statement) con.createStatement();
    String sql = "SELECT USERNAME,PASSWORD FROM LOGIN WHERE USERNAME='"+user+"';";
    ResultSet rs = stmt.executeQuery(sql);
    if(rs.next())
    {
     String Uname = rs.getString("Username");
     String Password = rs.getString("Password");
      JOptionPane.showMessageDialog(this,"Loged In Successfully");
                 this.dispose();
                 new Home(user).setVisible(true);
                 
   }
    else
     {
         JOptionPane.showMessageDialog(this,"Not yet Register\nPlaese REGISTER\nor\nLogin As Guest");
    }
    } catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jLabel3MouseReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exitb;
    private javax.swing.JLabel Exitbg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}