package mp3player;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.naming.spi.DirStateFactory;
import javax.sound.sampled.*;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.IconUIResource;
import javax.swing.table.DefaultTableModel;
import javazoom.jl.decoder.Equalizer;
import javazoom.jl.player.advanced.AdvancedPlayer;

/**
 *
 * @author Anhad
 */
public class MP3 extends javax.swing.JFrame implements ActionListener{
   String username;

    Mp3Player MC = new Mp3Player();
        private static Timer timer;

    public static int count;
public void actionPerformed(ActionEvent e) {
jProgressBar1.setMaximum((int) MC.songTotalLength);
 int n=jProgressBar1.getValue();
       // int random=(int) Math.round(Math.random()*0.5);


         if (n <=MC.songTotalLength)
    {
          n++;
                  
          jProgressBar1.setValue(n);
    }

    else
    {
        timer.stop();
            }
         
if(n==MC.songTotalLength){
    this.setVisible(false);
    try{
        Thread.sleep(1000);
    }catch(Exception a){}
    this.dispose();
    new Home().setVisible(true);
}
    }
    /** Creates new form start */
   
   public MP3()        
    {
        
        initComponents();     
      this.setOpacity((float) 0.5);
       
    }
    public MP3(String name)        
    {
        username=name;
        initComponents();
        
         visual.setVisible(false);
        start.setVisible(false);
        pause.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        visual = new javax.swing.JLabel();
        Display = new javax.swing.JLabel();
        Music = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Display1 = new javax.swing.JLabel();
        select = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        pause = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        stop = new javax.swing.JLabel();
        repeat = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.setBounds(new java.awt.Rectangle(400, 150, 0, 0));
        jDialog1.setMinimumSize(new java.awt.Dimension(640, 378));
        jDialog1.getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Playlist"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jDialog1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 590, 230);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton1);
        jButton1.setBounds(370, 310, 100, 25);

        jLabel7.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Playlist");
        jDialog1.getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 30, 290, 24);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2);
        jButton2.setBounds(170, 310, 100, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/textfield.png"))); // NOI18N
        jDialog1.getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 326, 41);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/black-felt-tape__1600x1600__96dpi.jpg"))); // NOI18N
        jDialog1.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 630, 340);

        visual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/Ironman-Jarvis-Boot-Animation.gif"))); // NOI18N
        visual.setFocusable(false);
        visual.setMinimumSize(new java.awt.Dimension(1000, 1000));
        visual.setPreferredSize(new java.awt.Dimension(1000, 10000));
        jDialog2.getContentPane().add(visual, java.awt.BorderLayout.CENTER);

        Display.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Display.setForeground(new java.awt.Color(255, 255, 255));
        Display.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mp 3 Player");
        setBounds(new java.awt.Rectangle(10000, 800, 0, 0));
        setMinimumSize(new java.awt.Dimension(200, 80));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 100));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Music.setForeground(new java.awt.Color(255, 255, 255));
        Music.setText("Media Player");
        getContentPane().add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 120, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Display1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Display1);
        Display1.setBounds(10, 20, 160, 20);

        select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/photo.jpg"))); // NOI18N
        select.setToolTipText("Select Music");
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectMouseReleased(evt);
            }
        });
        jPanel1.add(select);
        select.setBounds(310, 10, 40, 20);

        start.setBackground(new java.awt.Color(51, 51, 51));
        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/start1.jpg"))); // NOI18N
        start.setMinimumSize(new java.awt.Dimension(40, 40));
        start.setPreferredSize(new java.awt.Dimension(40, 40));
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                startMouseReleased(evt);
            }
        });
        jPanel1.add(start);
        start.setBounds(190, 10, 50, 40);

        pause.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pause.setMinimumSize(new java.awt.Dimension(20, 22));
        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pauseMouseReleased(evt);
            }
        });
        jPanel1.add(pause);
        pause.setBounds(170, 10, 80, 40);

        jSlider1.setMinorTickSpacing(5);
        jSlider1.setOpaque(false);
        jPanel1.add(jSlider1);
        jSlider1.setBounds(240, 10, 60, 20);

        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stopMouseReleased(evt);
            }
        });
        jPanel1.add(stop);
        stop.setBounds(200, 510, 20, 30);

        repeat.setToolTipText("Looping");
        repeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                repeatMouseReleased(evt);
            }
        });
        jPanel1.add(repeat);
        repeat.setBounds(190, 30, 20, 20);

        jProgressBar1.setMaximum(0);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(0, 0, 370, 10);

        jLabel9.setText("Song chooser");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 30, 80, 14);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(240, 10, 20, 50);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(180, 10, 20, 50);

        jLabel2.setText("Volume");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 20, 60, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 80));

        setSize(new java.awt.Dimension(370, 50));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseReleased

        
        
        MC.Resume();
        
        visual.setVisible(true);
        start.setVisible(false);
       
       

    }//GEN-LAST:event_startMouseReleased

    private void selectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseReleased
       long a = MC.songTotalLength;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files","mp3","mpeg3");
        JFileChooser chooser = new JFileChooser("C:\\Users\\DAV\\Desktop\\song");
        int returnVal = chooser.showOpenDialog(null);

        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            MC.stop();
            
            File myfile = chooser.getSelectedFile();
            String song = myfile + "";
            String name = chooser.getSelectedFile().getName();
timer=new Timer((int) a,this);
        timer.start();
        Display.setText(name);
            Display1.setText(name);
            MC.play(song);
            visual.setVisible(true);
            start.setVisible(false);
            pause.setVisible(true);
    }
        
    }//GEN-LAST:event_selectMouseReleased

    private void pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMouseReleased
        MC.pause();
        visual.setVisible(false);
        start.setVisible(true);
        

    }//GEN-LAST:event_pauseMouseReleased

    private void stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseReleased
       
        MC.stop();
        visual.setVisible(false);
        start.setVisible(true);
        

    }//GEN-LAST:event_stopMouseReleased

    private void repeatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repeatMouseReleased
switch(count)
{
    case 0:
        count = 1;
        
        break;
    case 1:
        count = 0;
        
        break;
}
    }//GEN-LAST:event_repeatMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        visual.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String song  = Display.getText();
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
try{
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Player", "root", "root");
    Statement stmt = (Statement) con.createStatement();
    String query = " select * from "+pos+";";
    ResultSet rs = stmt.executeQuery(query);
    
        while (rs.next()) {
            int count=0;
            
            String Playlist = rs.getString("Playlist");
model.addRow(new Object[]{Playlist});

        
}
}
catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
}    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }/**   
}     }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved
*/
     private void formMouseMoved(java.awt.event.MouseEvent evt) {                                
        // TODO add your handling code here:
         if(true){
     this.setOpacity(1);
         }else{
             this.setOpacity((float) 0.5);
         }
        
         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Display;
    public static javax.swing.JLabel Display1;
    private javax.swing.JLabel Music;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pause;
    private javax.swing.JLabel repeat;
    private javax.swing.JLabel select;
    private javax.swing.JLabel start;
    private javax.swing.JLabel stop;
    public static javax.swing.JLabel visual;
    // End of variables declaration//GEN-END:variables

   

    


}
