/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3player;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Anhad
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Exitb = new javax.swing.JLabel();
        Exitbg = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        Back = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(329, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(329, 500));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(35, 26, 50));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("First_Name");
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField1MouseReleased(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 210, 170, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 0, 30, 20);

        Exitb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Exitb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        Exitb.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Exitb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitbMouseReleased(evt);
            }
        });
        getContentPane().add(Exitb);
        Exitb.setBounds(310, 0, 20, 20);

        Exitbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/exitmedium.png"))); // NOI18N
        getContentPane().add(Exitbg);
        Exitbg.setBounds(-280, 0, 620, 20);

        jTextField2.setBackground(new java.awt.Color(35, 26, 50));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Last_Name");
        jTextField2.setBorder(null);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField2MouseReleased(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 260, 170, 20);

        jTextField3.setBackground(new java.awt.Color(35, 26, 50));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("E_Mail ID");
        jTextField3.setBorder(null);
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField3MouseReleased(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(60, 410, 170, 20);

        jTextField4.setBackground(new java.awt.Color(35, 26, 50));
        jTextField4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Username");
        jTextField4.setBorder(null);
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField4MouseReleased(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 160, 170, 20);

        jPasswordField1.setBackground(new java.awt.Color(35, 26, 50));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Password");
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseReleased(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(130, 360, 180, 20);

        jPasswordField2.setBackground(new java.awt.Color(35, 26, 50));
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setText("Password");
        jPasswordField2.setBorder(null);
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseReleased(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(40, 310, 180, 20);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 153, 255));
        Back.setText("<-- Back");
        Back.setToolTipText("");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(280, 30, 50, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/logo1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 20, 210, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/restextfield.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-80, 200, 380, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/textfield.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 250, 290, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/restextfield.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-70, 300, 330, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/textfield.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 350, 290, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/restextfield.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-60, 400, 330, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/textfield.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 150, 290, 40);

        jButton1.setBackground(new java.awt.Color(42, 26, 37));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 460, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/cell_light_hexagon_shadow_15345_602x339 (1).jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseReleased

    private void ExitbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbMouseReleased
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitbMouseReleased

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
        
        this.dispose();
        new Login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Username = jTextField4.getText();
String Firstname = jTextField1.getText();
String Lastname = jTextField2.getText();
String Email = jTextField3.getText();
String password = jPasswordField2.getText();
try{
    if(jTextField4.getText().equals("Username")||jTextField1.getText().equals("First_Name")||jTextField2.getText().equals("Last_Name")||jTextField3.getText().equals("E_Mail ID")||jPasswordField2.equals("Password")
    ||jPasswordField1.equals("Password")){
        JOptionPane.showMessageDialog(this, "Invalid Entry");
    }
    else if (jTextField3.getText().contains("@gmail.com")||jTextField3.getText().contains("@yahoo.com")||jTextField3.getText().contains("@rediff.com"))
    {
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Player", "root", "root");
    Statement stmt = (Statement) con.createStatement();
    String query = "insert into Login values ('"+Username+"','"+Firstname+"','"+Lastname+"','"+Email+"','"+password+"');";
    String querytwo = "create table "+Username+" (Playlist varchar(50));";
    stmt.executeUpdate(query);
    stmt.executeUpdate(querytwo);
    JOptionPane.showMessageDialog(this, "Register Successfully");
    this.dispose();
    new Login().setVisible(true);
}
}
catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseReleased
 /**String username = jTextField4.getText();

if(username.equals("Username")){
    jTextField4.setText(null);
    jTextField1.setText("First_Name");
    jTextField2.setText("Last_Name");
    jTextField3.setText("E_Mail ID");
    jPasswordField2.setText("Password");  
    jPasswordField1.setText("Password");  
    
}*/
    }//GEN-LAST:event_jTextField4MouseReleased

    private void jTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseReleased
 /**String Firstname = jTextField1.getText();

if(Firstname.equals("First_Name")){
    jTextField1.setText(null);
    jTextField4.setText("Username");
    jTextField2.setText("Last_Name");
    jTextField3.setText("E_Mail ID");
    jPasswordField2.setText("Password");  
    jPasswordField1.setText("Password");  
   
}    }//GEN-LAST:event_jTextField1MouseReleased
*/
    }
    private void jTextField2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseReleased
/**
 String Lastname = jTextField2.getText();

if(Lastname.equals("Last_Name")){
    jTextField1.setText("First_Name");
    jTextField4.setText("Username");
    jTextField2.setText(null);
    jTextField3.setText("E_Mail ID");
    jPasswordField2.setText("Password");  
    jPasswordField1.setText("Password");  
    
}*/
    }//GEN-LAST:event_jTextField2MouseReleased

    private void jTextField3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseReleased
/**
 String Email = jTextField3.getText();

if(Email.equals("E_Mail ID")){
    jTextField1.setText("First_Name");
    jTextField4.setText("Username");
    jTextField2.setText("Last_Name");
    jTextField3.setText(null);
    jPasswordField2.setText("Password");  
    jPasswordField1.setText("Password");  
    
}  */      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MouseReleased

    private void jPasswordField2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseReleased
 /**   String password = jPasswordField2.getText();

if(password.equals("Password")){
    jTextField1.setText("First_Name");
    jTextField4.setText("Username");
    jTextField2.setText("Last_Name");
    jTextField3.setText("E_Mail ID");
    jPasswordField2.setText(null);  
    jPasswordField1.setText("Password");  
    
}   */   // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2MouseReleased

    private void jPasswordField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseReleased
      /**   String cpassword = jPasswordField1.getText();

if(cpassword.equals("Password")){
    jTextField1.setText("First_Name");
    jTextField4.setText("Username");
    jTextField2.setText("Last_Name");
    jTextField3.setText("E_Mail ID");
    jPasswordField1.setText(null);  
    jPasswordField2.setText("Password");  
    
}   */// TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
/**if( jTextField1.getText().contains(null)||
    jTextField4.getText().contains(null)||
    jTextField2.getText().contains(null)||
    jTextField3.getText().contains(null)||
    jPasswordField1.getText().contains(null)||
    jPasswordField2.getText().contains(null)
   )
{
    jTextField1.setText("First_Name");
    jTextField4.setText("Username");
    jTextField2.setText("Last_Name");
    jTextField3.setText("E_Mail ID");
    jPasswordField1.setText("Password");  
    jPasswordField2.setText("Password"); 
}
*/
     }//GEN-LAST:event_jLabel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Exitb;
    private javax.swing.JLabel Exitbg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
