/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3player;

import javax.swing.ImageIcon;

/**
 *
 * @author Anhad
 */
public class Wallpaper extends javax.swing.JFrame {

     ImageIcon wall1 = new ImageIcon(getClass().getResource("/mp3player/wall1.jpg"));
     ImageIcon wall22 = new ImageIcon(getClass().getResource("/mp3player/new-background.png"));

    public Wallpaper() {
        initComponents();
        exittab.setVisible(false);
        logo.setVisible(false);
  
    }
   public Wallpaper(String name) {
        String username = name;
        initComponents();
        jLabel3.setText(username);    
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exitb = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();
        exittab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 563));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(950, 0, 30, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Hello,");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(930, 60, 60, 30);

        Exitb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Exitb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/mini.png"))); // NOI18N
        Exitb.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Exitb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitbMouseReleased(evt);
            }
        });
        getContentPane().add(Exitb);
        Exitb.setBounds(980, 0, 20, 20);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/logo1.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(0, 10, 210, 80);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 153, 255));
        Back.setText("<-- Back");
        Back.setToolTipText("");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(940, 30, 50, 20);

        wall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/walllicon1.jpg"))); // NOI18N
        wall.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                wallMouseReleased(evt);
            }
        });
        getContentPane().add(wall);
        wall.setBounds(140, 200, 290, 170);

        exittab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/exit.png"))); // NOI18N
        getContentPane().add(exittab);
        exittab.setBounds(0, 0, 1000, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/wallicon2.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 200, 292, 170);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Guest");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(820, 80, 170, 30);

        backg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3player/new-background.png"))); // NOI18N
        getContentPane().add(backg);
        backg.setBounds(0, 0, 1000, 563);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wallMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallMouseReleased
backg.setIcon(wall1); 
exittab.setVisible(true);
logo.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_wallMouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
    backg.setIcon(wall22);
    exittab.setVisible(false);
    logo.setVisible(false); 
    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseReleased

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
String user = jLabel3.getText();
        this.dispose();
        new Home(user).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseReleased

    private void ExitbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbMouseReleased
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitbMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wallpaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Exitb;
    private javax.swing.JLabel backg;
    private javax.swing.JLabel exittab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
